version: "3.7"

services:
  dev-server:
    build:
      context: .
      dockerfile: ./mock/docker/Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/api/node_modules
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - .:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
